### ISSUE TITLE
Add support for ESP32 "BluetoothSerial.h"?

### ISSUE THREAD

**Issue by ipsod** [lexus2k/tinyproto#33]
In case it would help, I can post a simple serial string loopback test using PyBluez on Python and BluetoothSerial.h on esp32.

I'd like to do the rest of the work, too, but the code in this library is a bit over my head and would take more work than I think I can afford right now.

**Comment by lexus2k** [comment]
Hi,

it depends on your case and the protocol you use in your project.
If you're talking about full-duplex protocol, you need to take care of `tiny_fd_get_tx_data` and `tiny_fd_run_rx` in your code.
The first one fill the buffer provided with the data to be sent over some communication channel (in your case Bluetooth SPP), and the second one parses the data you read from communication channel (Bluetooth SPP).

Similar technique is used by [ESP32 SPI example](https://github.com/lexus2k/tinyproto/tree/master/examples/esp32_idf/spi)
